// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtyduhrvoqxoxxgsgvgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0eWR1aHJ2b3F4b3h4Z3Nndmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTQ0NjQsImV4cCI6MjA3MTc5MDQ2NH0.JN3ox6dx6568SFug5--jD84T1C4HLEOHcmRiHRXapco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});